<p align="center"><strong><u>WAIVER, RELEASE AND INDEMNITY AGREEMENT</u></strong><br>
  <strong><u>TOURNAMENT OF CHAMPIONS CHARITY WORK  PROJECT</u></strong></p>
<p>This Release,  Waiver of Liability and Indemnity Agreement (&quot;Agreement&quot;) is made and  entered into effective ________(month), _____(date), 20___ (year), by and among  HEB Grocery Company, LP (&quot;HEB&quot;), the H-E-B Tournament of Champions  Charitable Trust (the &ldquo;TOC Trust&rdquo;), the Participating Organizations (as defined  below), and the undersigned individual (&ldquo;Participant&rdquo;).  </p>
<p>            Whereas,  HEB will be sponsoring and the TOC Trust will be hosting the HEB Tournament of  Champions (the &ldquo;TOC&rdquo;) and related activities, a charitable fundraiser  benefitting various and numerous charities throughout the state of Texas, on or  around June 6, 2019;  </p>
<p>Whereas, the TOC  includes Charity Work Projects (the &ldquo;Charity Projects&rdquo;) held at several  locations in the Greater San Antonio area, including but not limited to those hosted  by the following participating organizations: Homes for Our Troops, the San  Antonio Food Bank, SAGE San Antonio, Kinetic Kids, Ella Austin Community Center,  Sunshine Cottage School for Deaf Children, and Family Violence Prevention  Services (collectively, the &ldquo;Participating Organizations&rdquo;); </p>
<p>Whereas, the TOC  and the Charity Projects include various activities designed to assist and  better the community and individuals in need, including but not limited to,  building fences, landscaping, assembling furniture, distributing food,  painting, roofing, building and installing storage sheds, benches, and tables,  picking up litter, and general cleaning; and</p>
<p>Whereas, Participant  has volunteered to participate in the TOC and/or the Charity Projects and has  agreed to release the sponsoring and hosting entities from any liability  associated therewith;</p>
<p> NOW, THEREFORE, in consideration of the  covenants and mutual promises herein contained, and other consideration, the  parties hereby agree as follow:<strong><u>  </u></strong></p>
<p>1.         In consideration for my participation  in the TOC and/or the Charity Projects, <strong>I HEREBY </strong><strong>release, waive, discharge and covenant not to sue, HEB,  the toc trust, THE PARTICIPATING ORGANIZATIONS, AND EACH OF THEIR RESPECTIVE affiliates,  officers, DIRECTORS, SHAREHOLDERS, agents, servants, representatives and  employees (hereinafter referred to collectively as the &ldquo;Released Parties&rdquo;) from  any and all liabilities, claims, demands, actions and causes of action  whatsoever arising out of or related to any loss, damage, (including but not  limited to property damage to any personal or real property), personal injury,  including death, that may be sustained by me, or any of the property belonging  to me, whether caused by the negligence of the Released Parties, other parTicipants,  attendees or otherwise, while participating in the </strong><strong>TOC AND/OR  THE CHARITY PROJECTS,</strong><strong> or while in, on or upon the premises where the TOC OR THE CHARITY </strong><strong>PROJECTS</strong><strong> ARE being conducted.</strong></p>
<p>2.         I am aware that during the course of my  participation in the TOC and/or the Charity Projects, I may be exposed to a  variety of potential hazards, and that I should not participate unless medically  able and properly trained.  I assume all  risks associated with these events including, but not limited to: property  damage, personal injury, death, health conditions and ailments, falls, contact  with other participants, all such risks being known and appreciated by me.<strong> </strong>I am further aware of the type and  nature of the work associated with the TOC and/or the Charity Projects and will  only participate where I am knowledgeable, have proper training (if  applicable), and understand the associated work.<strong> </strong>I hereby elect to voluntarily participate in the TOC and/or the  Charity Projects with full knowledge that my participation may be hazardous to me.   <strong>I  voluntarily assume full responsibility for any risks of loss, property damage  or personal injury, including death, that may be sustained by me or any loss or  damage to property owned by me as a result of my participation in the TOC  AND/OR THE CHARITY </strong><strong>PROJECTS</strong><strong>, whether caused by the negligence of the Released  Parties or otherwise.</strong>  I also  agree that for the duration of the TOC and/or the Charity Projects, I will  comply with all state, county and city laws.</p>
<p>3.         <strong>I FURTHER HEREBY AGREE TO INDEMNIFY AND HOLD HARMLESS  THE RELEASED PARTIES FROM ANY LOSS, LIABILITY, CLAIMS, DAMAGE OR COSTS,  INCLUDING COURT COSTS AND ATTORNEY FEES, THAT THEY MAY INCUR DUE TO MY PARTICIPATION  IN THE TOC AND/OR THE CHARITY PROJECTS, WHETHER CAUSED BY NEGLIGENCE OF THE Released Parties OR OTHERWISE.</strong></p>
<p>4.         It is my express intent that this <strong>WAIVER OF  LIABILITY AND INDEMNITY AGREEMENT </strong>shall also bind the members of my  family and/or spouse, if I am alive, and my heirs, assigns and personal  representative, if I am deceased, and shall be deemed as a <strong>release, waiver, discharge and covenant not to sue  the above-named Released Parties.  </strong>I  hereby further agree that this Waiver of Liability and Indemnity Agreement  shall be construed in accordance with the laws of the State of Texas.</p>
<p>5.         By  signing this release or manifesting my consent electronically (e.g., by  clicking &ldquo;I Accept&rdquo; or clicking a corresponding checkbox), I acknowledge and  represent that I have read the foregoing agreement in full, that I understand  it and sign it voluntarily as my own free act and deed; that no oral  representations, statements, or inducements, apart from the foregoing written  agreement, have been made; that I am at least eighteen (18) years of age and  fully competent; and that I execute this release for full, adequate and  complete consideration fully intending to be bound by same. 
</p>

